import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import '../../../core/l10n/app_localizations.dart';
import '../../../core/theme/tokens.dart';
import '../../../core/widgets/widgets.dart';

/// `/welcome` (02 §4.1). The install ID is generated by `appSettingsProvider`
/// on first launch.
class WelcomeScreen extends StatelessWidget {
  const WelcomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    final theme = Theme.of(context);
    return Scaffold(
      body: PinnedBottomLayout(
        bottom: [
          PrimaryButton(
            key: const Key('welcome.continue'),
            label: l10n.commonContinue,
            onPressed: () => context.go('/invite'),
          ),
        ],
        children: [
          const SizedBox(height: AppSpacing.xxl),
          Text(
            l10n.appTitle,
            style: theme.textTheme.titleLarge?.copyWith(
              color: AppColors.indigo,
            ),
          ),
          const SizedBox(height: AppSpacing.xl),
          Semantics(
            header: true,
            child: Text(
              l10n.welcomeTitle,
              style: theme.textTheme.headlineMedium,
            ),
          ),
          const SizedBox(height: AppSpacing.lg),
          Text(l10n.welcomeBody, style: theme.textTheme.bodyLarge),
          const SizedBox(height: AppSpacing.xl),
          Container(
            padding: const EdgeInsets.all(AppSpacing.lg),
            decoration: const BoxDecoration(
              color: AppColors.indigoTint,
              borderRadius: AppRadii.cardRadius,
            ),
            child: IndependenceNotice(text: l10n.welcomeIndependence),
          ),
        ],
      ),
    );
  }
}
