// Writes Android vector/XML brand resources from the master geometry (variant E).
// usage: node android-xml.mjs <repoRoot>
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { variants, C } from './variants.mjs';

const root = process.argv[2];
const res = join(root, 'apps/mobile/android/app/src/main/res');
const put = (f, s) => { mkdirSync(dirname(join(res, f)), { recursive: true }); writeFileSync(join(res, f), s.trim() + '\n'); };
const M = variants.E;
const [cx, cy, r] = M.dot;
const dotPath = `M${cx - r},${cy} a${r},${r} 0 1,0 ${2 * r},0 a${r},${r} 0 1,0 ${-2 * r},0`;
const SRC = '<!-- Generated by apps/mobile/tool/brand/android-xml.mjs from docs/brand/mark.svg. -->';

// Glyph (route + dot) in a group that maps the 100-unit mark onto the viewport.
function glyphVector({ vp, dp, scale, offset, route, dot }) {
  return `<?xml version="1.0" encoding="utf-8"?>
${SRC}
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${dp}dp" android:height="${dp}dp"
    android:viewportWidth="${vp}" android:viewportHeight="${vp}">
    <group android:translateX="${offset}" android:translateY="${offset}"
        android:scaleX="${scale}" android:scaleY="${scale}">
        <path android:pathData="${M.path}" android:fillColor="#00000000"
            android:strokeColor="${route}" android:strokeWidth="${M.stroke}"
            android:strokeLineCap="round" android:strokeLineJoin="round"/>
        <path android:pathData="${dotPath}" android:fillColor="${dot}"/>
    </group>
</vector>`;
}

// Adaptive icon: 108 dp canvas; the mark's 100-unit square maps onto the 72 dp
// visible area (offset 18), so the glyph (x 31–78, y 34–75) sits inside the 66 dp
// safe zone (21–87).
const LAUNCH = { vp: 108, dp: 108, scale: 0.72, offset: 18 };
put('drawable/ic_launcher_foreground.xml', glyphVector({ ...LAUNCH, route: C.white, dot: C.sunrise }));
put('drawable/ic_launcher_monochrome.xml', glyphVector({ ...LAUNCH, route: '#FFFFFFFF', dot: '#FFFFFFFF' }));
for (const f of ['ic_launcher', 'ic_launcher_round']) {
  put(`mipmap-anydpi-v26/${f}.xml`, `<?xml version="1.0" encoding="utf-8"?>
${SRC}
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/brand_primary"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>
</adaptive-icon>`);
}

// Status-bar icon: 24 dp white silhouette; glyph scaled to fill ~22 dp.
put('drawable/ic_stat_saarthee.xml', glyphVector({ vp: 100, dp: 24, scale: 1.3, offset: -15, route: '#FFFFFFFF', dot: '#FFFFFFFF' }));

// Android 12+ splash icon: 288 dp canvas, content inside the 192 dp circle
// (no icon background). Mark scaled 2.0 (offset 44); farthest point ~80 dp from centre.
const SPLASH = { vp: 288, dp: 288, scale: 2, offset: 44 };
put('drawable/splash_mark.xml', glyphVector({ ...SPLASH, route: C.white, dot: C.sunrise }));
put('drawable-night/splash_mark.xml', glyphVector({ ...SPLASH, route: '#7BD3A6', dot: C.sunrise }));

put('values/colors.xml', `<?xml version="1.0" encoding="utf-8"?>
${SRC}
<resources>
    <color name="brand_primary">${C.primary}</color>
    <color name="brand_sunrise">${C.sunrise}</color>
    <color name="splash_background">${C.primary}</color>
</resources>`);
put('values-night/colors.xml', `<?xml version="1.0" encoding="utf-8"?>
${SRC}
<resources>
    <color name="splash_background">#131C18</color>
</resources>`);

// Pre-12 splash: background colour + centred PNG mark (bitmap works on API 21+).
put('drawable/launch_background.xml', `<?xml version="1.0" encoding="utf-8"?>
${SRC}
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/splash_background"/>
    <item>
        <bitmap android:gravity="center" android:src="@drawable/launch_mark"/>
    </item>
</layer-list>`);
console.log('ok');
