import { steps, type ServiceSeed } from './services-types';

/** Health, education and transport services (TASK-12 §5.2 seed table, rows 8–12). */
export const SERVICES_B: readonly ServiceSeed[] = [
  {
    slug: 'amc-hospitals',
    category: 'health',
    nameEn: 'AMC hospitals and health department',
    nameGu: 'AMC હોસ્પિટલો અને આરોગ્ય વિભાગ',
    department: 'Health',
    departmentGu: 'આરોગ્ય વિભાગ',
    summaryEn: 'AMC-run hospitals and the health department’s services, with addresses and contacts.',
    summaryGu: 'AMC સંચાલિત હોસ્પિટલો અને આરોગ્ય વિભાગની સેવાઓ, સરનામાં અને સંપર્ક સાથે.',
    howToEn: steps(
      'Open the AMC health department page.',
      'Find the hospital or service you need and note its address.',
      'Visit in person; carry an ID and any earlier reports.',
    ),
    howToGu: steps(
      'AMC આરોગ્ય વિભાગનું પેજ ખોલો.',
      'જરૂરી હોસ્પિટલ કે સેવા શોધીને સરનામું લખી લો.',
      'રૂબરૂ જાઓ; ઓળખપત્ર અને અગાઉના રિપોર્ટ સાથે રાખો.',
    ),
    url: 'https://ahmedabadcity.gov.in/StaticPage/health_department',
    online: false,
    visitWardOffice: false,
    sortOrder: 10,
    isActive: true,
  },
  {
    slug: 'urban-health-centres',
    category: 'health',
    nameEn: 'Urban health centres',
    nameGu: 'અર્બન હેલ્થ સેન્ટર',
    department: 'Health',
    departmentGu: 'આરોગ્ય વિભાગ',
    summaryEn: 'Neighbourhood health centres for check-ups, vaccinations and mother-and-child care.',
    summaryGu: 'તપાસ, રસીકરણ અને માતા-બાળ સંભાળ માટે વિસ્તારના આરોગ્ય કેન્દ્રો.',
    howToEn: steps(
      'Open the AMC urban health centres page.',
      'Find the centre nearest to your home.',
      'Visit during its working hours with an ID.',
    ),
    howToGu: steps(
      'AMCનું અર્બન હેલ્થ સેન્ટર પેજ ખોલો.',
      'તમારા ઘરની નજીકનું કેન્દ્ર શોધો.',
      'કામના સમયમાં ઓળખપત્ર લઈને જાઓ.',
    ),
    url: 'https://ahmedabadcity.gov.in/SP/UrbanHealthCenters',
    online: false,
    visitWardOffice: false,
    sortOrder: 20,
    isActive: true,
  },
  {
    // Not verified on 2026-10-03: seeded inactive until staff confirm the official URL (§5.6).
    slug: 'amc-schools',
    category: 'education',
    nameEn: 'AMC primary schools',
    nameGu: 'AMC પ્રાથમિક શાળાઓ',
    department: 'School Board',
    departmentGu: 'શાળા બોર્ડ',
    summaryEn: 'Primary schools run by the AMC school board.',
    summaryGu: 'AMC શાળા બોર્ડ સંચાલિત પ્રાથમિક શાળાઓ.',
    howToEn: steps('Open the official AMC school board page.', 'Find the school nearest to you.', 'Visit the school for admission.'),
    howToGu: steps('AMC શાળા બોર્ડનું સત્તાવાર પેજ ખોલો.', 'તમારી નજીકની શાળા શોધો.', 'પ્રવેશ માટે શાળાની મુલાકાત લો.'),
    url: 'https://ahmedabadcity.gov.in/',
    online: false,
    visitWardOffice: false,
    sortOrder: 10,
    isActive: false,
  },
  {
    slug: 'brts',
    category: 'transport',
    nameEn: 'Janmarg BRTS routes and passes',
    nameGu: 'જનમાર્ગ BRTS રૂટ અને પાસ',
    department: 'Ahmedabad Janmarg Ltd',
    departmentGu: 'અમદાવાદ જનમાર્ગ લિમિટેડ',
    summaryEn: 'Routes, timings and passes for the Janmarg BRTS bus network.',
    summaryGu: 'જનમાર્ગ BRTS બસ નેટવર્કના રૂટ, સમય અને પાસ.',
    howToEn: steps(
      'Open the Janmarg BRTS website.',
      'Check the route map and timings for your trip.',
      'See the pass options and where to buy them.',
    ),
    howToGu: steps('જનમાર્ગ BRTSની વેબસાઇટ ખોલો.', 'તમારી મુસાફરી માટે રૂટ નકશો અને સમય જુઓ.', 'પાસના વિકલ્પો અને ક્યાંથી મળે તે જુઓ.'),
    url: 'https://www.ahmedabadbrts.org',
    online: true,
    visitWardOffice: false,
    sortOrder: 10,
    isActive: true,
  },
  {
    slug: 'amts',
    category: 'transport',
    nameEn: 'AMTS city buses',
    nameGu: 'AMTS શહેરી બસ',
    department: 'Ahmedabad Municipal Transport Service',
    departmentGu: 'અમદાવાદ મ્યુનિસિપલ ટ્રાન્સપોર્ટ સર્વિસ',
    summaryEn: 'AMTS bus routes and passes across the city.',
    summaryGu: 'શહેરભરના AMTS બસ રૂટ અને પાસ.',
    howToEn: steps(
      'Open the AMTS page on the AMC website.',
      'Find your route and stop.',
      'Buy a pass at an AMTS pass centre if you travel often.',
    ),
    howToGu: steps('AMC વેબસાઇટ પર AMTSનું પેજ ખોલો.', 'તમારો રૂટ અને સ્ટોપ શોધો.', 'રોજ મુસાફરી કરતા હો તો AMTS પાસ સેન્ટરથી પાસ લો.'),
    url: 'https://ahmedabadcity.gov.in/SP/AMTS',
    online: false,
    visitWardOffice: false,
    sortOrder: 20,
    isActive: true,
  },
];
