import { steps, type ServiceSeed } from './services-types';

/** Leisure, information and business services (TASK-12 §5.2 seed table, rows 13–18). */
export const SERVICES_C: readonly ServiceSeed[] = [
  {
    slug: 'kankaria-tickets',
    category: 'leisure',
    nameEn: 'Kankaria Lakefront tickets',
    nameGu: 'કાંકરિયા લેકફ્રન્ટ ટિકિટ',
    department: 'Kankaria Lakefront',
    departmentGu: 'કાંકરિયા લેકફ્રન્ટ',
    summaryEn: 'Book entry and attraction tickets for Kankaria Lakefront online.',
    summaryGu: 'કાંકરિયા લેકફ્રન્ટની પ્રવેશ અને આકર્ષણોની ટિકિટ ઓનલાઇન બુક કરો.',
    howToEn: steps('Open the Kankaria tickets website.', 'Choose the date and attractions.', 'Pay online and show the ticket at the gate.'),
    howToGu: steps('કાંકરિયા ટિકિટ વેબસાઇટ ખોલો.', 'તારીખ અને આકર્ષણો પસંદ કરો.', 'ઓનલાઇન ચૂકવીને ગેટ પર ટિકિટ બતાવો.'),
    url: 'https://www.kankarialaketickets.com/',
    online: true,
    visitWardOffice: false,
    sortOrder: 10,
    isActive: true,
  },
  {
    slug: 'riverfront',
    category: 'leisure',
    nameEn: 'Sabarmati Riverfront',
    nameGu: 'સાબરમતી રિવરફ્રન્ટ',
    department: 'Sabarmati Riverfront Development Corporation',
    departmentGu: 'સાબરમતી રિવરફ્રન્ટ ડેવલપમેન્ટ કોર્પોરેશન',
    summaryEn: 'Parks, walkways and events along the Sabarmati Riverfront.',
    summaryGu: 'સાબરમતી રિવરફ્રન્ટ પરના બગીચા, વૉકવે અને કાર્યક્રમો.',
    howToEn: steps('Open the Sabarmati Riverfront website.', 'See the parks, timings and events.', 'Visit in person; some events need tickets.'),
    howToGu: steps('સાબરમતી રિવરફ્રન્ટની વેબસાઇટ ખોલો.', 'બગીચા, સમય અને કાર્યક્રમો જુઓ.', 'રૂબરૂ જાઓ; કેટલાક કાર્યક્રમો માટે ટિકિટ જોઈએ.'),
    url: 'https://www.sabarmatiriverfront.com/',
    online: false,
    visitWardOffice: false,
    sortOrder: 20,
    isActive: true,
  },
  {
    slug: 'rti',
    category: 'information',
    nameEn: 'Right to Information (RTI) request',
    nameGu: 'માહિતી અધિકાર (RTI) અરજી',
    department: 'RTI Cell',
    departmentGu: 'RTI શાખા',
    summaryEn: 'How to ask AMC for information under the RTI Act and whom to address.',
    summaryGu: 'RTI કાયદા હેઠળ AMC પાસેથી માહિતી કેવી રીતે માગવી અને કોને અરજી કરવી.',
    howToEn: steps(
      'Open the AMC RTI page and find the right public information officer.',
      'Write your questions clearly in a short application.',
      'Submit it at the ward office or the department named on the page.',
      'Keep the acknowledgement; a reply is due within the time the Act sets.',
    ),
    howToGu: steps(
      'AMC નું RTI પેજ ખોલીને યોગ્ય જાહેર માહિતી અધિકારી શોધો.',
      'ટૂંકી અરજીમાં તમારા પ્રશ્નો સ્પષ્ટ લખો.',
      'વોર્ડ ઑફિસ કે પેજ પર જણાવેલા વિભાગમાં જમા કરો.',
      'પહોંચ સાચવો; કાયદામાં નક્કી સમયમાં જવાબ આપવાનો હોય છે.',
    ),
    url: 'https://ahmedabadcity.gov.in/StaticPage/RTI',
    online: false,
    visitWardOffice: true,
    sortOrder: 10,
    isActive: true,
  },
  {
    slug: 'civic-centres',
    category: 'information',
    nameEn: 'City civic centres',
    nameGu: 'શહેરના સિવિક સેન્ટર',
    department: 'Civic Centres',
    departmentGu: 'સિવિક સેન્ટર',
    summaryEn: 'Addresses of AMC civic centres for certificates, tax and other counter services.',
    summaryGu: 'પ્રમાણપત્ર, વેરા અને અન્ય કાઉન્ટર સેવાઓ માટે AMC સિવિક સેન્ટરનાં સરનામાં.',
    howToEn: steps('Open the AMC civic centres page.', 'Find the centre nearest to you.', 'Visit during working hours with your documents.'),
    howToGu: steps('AMC નું સિવિક સેન્ટર પેજ ખોલો.', 'તમારી નજીકનું સેન્ટર શોધો.', 'કામના સમયમાં દસ્તાવેજો લઈને જાઓ.'),
    url: 'https://ahmedabadcity.gov.in/SP/CityCivicCenters',
    online: false,
    visitWardOffice: true,
    sortOrder: 20,
    isActive: true,
  },
  {
    slug: 'amc-online-services',
    category: 'information',
    nameEn: 'All AMC online services',
    nameGu: 'AMC ની બધી ઓનલાઇન સેવાઓ',
    department: 'AMC',
    departmentGu: 'AMC',
    summaryEn: 'AMC’s own list of every service you can use online.',
    summaryGu: 'ઓનલાઇન વાપરી શકાય તેવી દરેક સેવાની AMC ની પોતાની યાદી.',
    howToEn: steps('Open the AMC online services page.', 'Pick the service you need.', 'Follow the steps on that service’s page.'),
    howToGu: steps('AMC નું ઓનલાઇન સેવાઓ પેજ ખોલો.', 'જરૂરી સેવા પસંદ કરો.', 'એ સેવાના પેજ પરનાં પગલાં અનુસરો.'),
    url: 'https://ahmedabadcity.gov.in/SP/UseOnlineServices',
    online: true,
    visitWardOffice: false,
    sortOrder: 30,
    isActive: true,
  },
  {
    slug: 'tenders',
    category: 'business',
    nameEn: 'AMC tenders',
    nameGu: 'AMC ટેન્ડર',
    department: 'AMC e-Tendering (nProcure)',
    departmentGu: 'AMC ઇ-ટેન્ડરિંગ (nProcure)',
    summaryEn: 'AMC publishes its tenders on the nProcure e-tendering portal.',
    summaryGu: 'AMC તેનાં ટેન્ડર nProcure ઇ-ટેન્ડરિંગ પોર્ટલ પર પ્રકાશિત કરે છે.',
    howToEn: steps('Open the nProcure portal.', 'Search for Ahmedabad Municipal Corporation tenders.', 'Register on the portal to download papers and bid.'),
    howToGu: steps('nProcure પોર્ટલ ખોલો.', 'અમદાવાદ મ્યુનિસિપલ કોર્પોરેશનનાં ટેન્ડર શોધો.', 'દસ્તાવેજ મેળવવા અને બિડ કરવા પોર્ટલ પર નોંધણી કરો.'),
    url: 'https://tender.nprocure.com',
    online: true,
    visitWardOffice: false,
    sortOrder: 10,
    isActive: true,
  },
];
