import { steps, type ServiceSeed } from './services-types';

/** Tax, certificates, building and health services (TASK-12 §5.2 seed table, rows 1–7). */
export const SERVICES_A: readonly ServiceSeed[] = [
  {
    slug: 'property-tax-pay',
    category: 'tax',
    nameEn: 'Pay property tax',
    nameGu: 'મિલકત વેરો ભરો',
    department: 'Property Tax',
    departmentGu: 'મિલકત વેરા વિભાગ',
    summaryEn: 'Find your property tax dues by tenement number and pay online.',
    summaryGu: 'ટેનામેન્ટ નંબરથી તમારો બાકી મિલકત વેરો જુઓ અને ઓનલાઇન ભરો.',
    howToEn: steps(
      'Open the AMC property tax page.',
      'Enter your tenement number and tap Search.',
      'Check the owner name and amount due.',
      'Pay by UPI, card or net banking.',
      'Download the receipt and keep it.',
    ),
    howToGu: steps(
      'AMCનું મિલકત વેરા પેજ ખોલો.',
      'તમારો ટેનામેન્ટ નંબર લખો અને Search દબાવો.',
      'માલિકનું નામ અને બાકી રકમ તપાસો.',
      'UPI, કાર્ડ કે નેટ બેન્કિંગથી ચૂકવણી કરો.',
      'રસીદ ડાઉનલોડ કરીને સાચવી રાખો.',
    ),
    url: 'https://ahmedabadcity.gov.in/PTAX/DuesSearch',
    online: true,
    visitWardOffice: false,
    sortOrder: 10,
    isActive: true,
  },
  {
    slug: 'property-tax-bill',
    category: 'tax',
    nameEn: 'See your property tax bill',
    nameGu: 'તમારું મિલકત વેરા બિલ જુઓ',
    department: 'Property Tax',
    departmentGu: 'મિલકત વેરા વિભાગ',
    summaryEn: 'View or download this year’s property tax bill for your tenement.',
    summaryGu: 'તમારા ટેનામેન્ટનું આ વર્ષનું મિલકત વેરા બિલ જુઓ કે ડાઉનલોડ કરો.',
    howToEn: steps(
      'Open the AMC property tax bill page.',
      'Enter your tenement number.',
      'Open the bill and check the details.',
      'Download or print it if you need a copy.',
    ),
    howToGu: steps(
      'AMCનું મિલકત વેરા બિલ પેજ ખોલો.',
      'તમારો ટેનામેન્ટ નંબર લખો.',
      'બિલ ખોલીને વિગતો તપાસો.',
      'નકલ જોઈએ તો ડાઉનલોડ કે પ્રિન્ટ કરો.',
    ),
    url: 'https://ahmedabadcity.gov.in/PTAX/Bill',
    online: true,
    visitWardOffice: false,
    sortOrder: 20,
    isActive: true,
  },
  {
    slug: 'property-name-transfer',
    category: 'tax',
    nameEn: 'Pay property name-transfer fee',
    nameGu: 'મિલકત નામ ટ્રાન્સફર ફી ભરો',
    department: 'Property Tax',
    departmentGu: 'મિલકત વેરા વિભાગ',
    summaryEn: 'Look up and pay the name-transfer charge after buying or inheriting a property.',
    summaryGu: 'મિલકત ખરીદ્યા કે વારસામાં મળ્યા પછી નામ ટ્રાન્સફરનો ચાર્જ જુઓ અને ભરો.',
    howToEn: steps(
      'Open the AMC name-transfer charge page.',
      'Enter your tenement number and search.',
      'Pay the charge shown online and save the receipt.',
      'Take the receipt and your documents to the ward office if they ask you to.',
    ),
    howToGu: steps(
      'AMCનું નામ ટ્રાન્સફર ચાર્જ પેજ ખોલો.',
      'ટેનામેન્ટ નંબર લખીને શોધો.',
      'બતાવેલો ચાર્જ ઓનલાઇન ભરો અને રસીદ સાચવો.',
      'જરૂર પડે તો રસીદ અને દસ્તાવેજો લઈને વોર્ડ ઓફિસ જાઓ.',
    ),
    url: 'https://ahmedabadcity.gov.in/PTAX/TSFChargeSearch',
    online: true,
    visitWardOffice: true,
    sortOrder: 30,
    isActive: true,
  },
  {
    slug: 'professional-tax',
    category: 'tax',
    nameEn: 'Professional tax',
    nameGu: 'વ્યવસાય વેરો',
    department: 'Professional Tax',
    departmentGu: 'વ્યવસાય વેરા વિભાગ',
    summaryEn: 'Register for and pay professional tax as an employer or self-employed person.',
    summaryGu: 'નોકરીદાતા કે સ્વરોજગાર તરીકે વ્યવસાય વેરા માટે નોંધણી કરો અને ભરો.',
    howToEn: steps(
      'Open the AMC professional tax page.',
      'Choose registration or payment.',
      'Fill in your details as the page asks.',
      'Pay online and keep the receipt.',
    ),
    howToGu: steps(
      'AMCનું વ્યવસાય વેરા પેજ ખોલો.',
      'નોંધણી કે ચૂકવણી પસંદ કરો.',
      'પેજ પૂછે તે પ્રમાણે વિગતો ભરો.',
      'ઓનલાઇન ચૂકવણી કરો અને રસીદ રાખો.',
    ),
    url: 'https://ahmedabadcity.gov.in/StaticPage/professional_tax',
    online: true,
    visitWardOffice: false,
    sortOrder: 40,
    isActive: true,
  },
  {
    slug: 'birth-death-search',
    category: 'certificates',
    nameEn: 'Find a birth or death registration',
    nameGu: 'જન્મ કે મરણની નોંધ શોધો',
    department: 'Births and Deaths Registration',
    departmentGu: 'જન્મ-મરણ નોંધણી વિભાગ',
    summaryEn: 'Search AMC birth and death records; collect certified copies at a civic centre.',
    summaryGu: 'AMCના જન્મ-મરણના રેકોર્ડ શોધો; પ્રમાણિત નકલ સિવિક સેન્ટરથી મેળવો.',
    howToEn: steps(
      'Open the AMC registration search page.',
      'Choose birth or death and enter the details you know.',
      'Note the registration number from the result.',
      'Visit a civic centre or your ward office with ID for a certified copy.',
    ),
    howToGu: steps(
      'AMCનું નોંધણી શોધ પેજ ખોલો.',
      'જન્મ કે મરણ પસંદ કરીને જાણતા હો તે વિગતો લખો.',
      'પરિણામમાંથી નોંધણી નંબર લખી લો.',
      'પ્રમાણિત નકલ માટે ઓળખપત્ર લઈને સિવિક સેન્ટર કે વોર્ડ ઓફિસ જાઓ.',
    ),
    url: 'https://ahmedabadcity.gov.in/OnlineSerWithoutLogin/RegistrationSearch',
    online: true,
    visitWardOffice: true,
    sortOrder: 10,
    isActive: true,
  },
  {
    slug: 'building-permission',
    category: 'building',
    nameEn: 'Building plan permission (TDO)',
    nameGu: 'બાંધકામ પ્લાન મંજૂરી (TDO)',
    department: 'Town Development',
    departmentGu: 'ટાઉન ડેવલપમેન્ટ વિભાગ',
    summaryEn: 'How to apply for building plan permission through AMC’s Town Development department.',
    summaryGu: 'AMCના ટાઉન ડેવલપમેન્ટ વિભાગ મારફતે બાંધકામ પ્લાન મંજૂરી માટે અરજી કેવી રીતે કરવી.',
    howToEn: steps(
      'Open the AMC building permission page.',
      'Read the list of documents and plans needed.',
      'Apply online through the link on that page, usually with your architect.',
      'Track the application status on the same portal.',
    ),
    howToGu: steps(
      'AMCનું બાંધકામ મંજૂરી પેજ ખોલો.',
      'જરૂરી દસ્તાવેજો અને પ્લાનની યાદી વાંચો.',
      'એ પેજ પરની લિંકથી ઓનલાઇન અરજી કરો, સામાન્ય રીતે આર્કિટેક્ટ સાથે.',
      'એ જ પોર્ટલ પર અરજીની સ્થિતિ જુઓ.',
    ),
    url: 'https://ahmedabadcity.gov.in/StaticPage/buildingPermission_dept',
    online: true,
    visitWardOffice: false,
    sortOrder: 10,
    isActive: true,
  },
  {
    slug: 'fire-noc',
    category: 'building',
    nameEn: 'Fire NOC (AMC Fire & Emergency Services)',
    nameGu: 'ફાયર NOC (AMC ફાયર અને ઇમરજન્સી સેવા)',
    department: 'Fire & Emergency Services',
    departmentGu: 'ફાયર અને ઇમરજન્સી સેવા વિભાગ',
    summaryEn: 'Fire safety no-objection certificates for buildings, from AMC’s fire department.',
    summaryGu: 'ઇમારતો માટે ફાયર સેફ્ટી નો-ઓબ્જેક્શન સર્ટિફિકેટ, AMC ફાયર વિભાગ તરફથી.',
    howToEn: steps(
      'Open the AMC Fire & Emergency Services page.',
      'Find the Fire NOC section and the documents it lists.',
      'Apply online through the link on that page.',
      'Keep your application number to track it.',
    ),
    howToGu: steps(
      'AMC ફાયર અને ઇમરજન્સી સેવાનું પેજ ખોલો.',
      'ફાયર NOC વિભાગ અને તેમાં જણાવેલા દસ્તાવેજો શોધો.',
      'એ પેજ પરની લિંકથી ઓનલાઇન અરજી કરો.',
      'ટ્રેક કરવા માટે અરજી નંબર સાચવો.',
    ),
    url: 'https://ahmedabadcity.gov.in/StaticPage/fire_dept',
    online: true,
    visitWardOffice: false,
    sortOrder: 20,
    isActive: true,
  },
];
